import { create } from 'zustand';

export type AppLanguage = 'km' | 'en';

const translations: Record<string, [string, string]> = {
  Home: ['ទំព័រដើម', 'Home'],
  Explore: ['រុករក', 'Explore'],
  Short: ['វីដេអូខ្លី', 'Shorts'],
  Download: ['ទាញយក', 'Downloads'],
  Downloads: ['ទាញយក', 'Downloads'],
  Me: ['គណនី', 'Me'],
  Donghua: ['រឿងចិន', 'Donghua'],
  Anime: ['រឿងជប៉ុន', 'Anime'],
  Drama: ['រឿងភាគ', 'Drama'],
  Movies: ['ភាពយន្ត', 'Movies'],
  'For You': ['សម្រាប់អ្នក', 'For You'],
  'Popular anime': ['អានីមេពេញនិយម', 'Popular anime'],
  'Donghua for you': ['រឿងចិនសម្រាប់អ្នក', 'Donghua for you'],
  'Movies & drama': ['ភាពយន្ត និងរឿងភាគ', 'Movies & drama'],
  'Popular on Huang Anime': ['រឿងពេញនិយមនៅ Huang Anime', 'Popular on Huang Anime'],
  'Trending Chinese Animation': ['រឿងចិនកំពុងពេញនិយម', 'Trending Chinese Animation'],
  'Latest Release': ['រឿងចេញថ្មីៗ', 'Latest Release'],
  More: ['មើលបន្ថែម', 'More'],
  Featured: ['ពិសេស', 'Featured'],
  'Search anime and drama': ['ស្វែងរកអានីមេ និងរឿងភាគ', 'Search anime and drama'],
  VIP: ['VIP', 'VIP'],
  'My List': ['បញ្ជីរបស់ខ្ញុំ', 'My List'],
  History: ['ប្រវត្តិទស្សនា', 'History'],
  'VIP Plans': ['កញ្ចប់ VIP', 'VIP Plans'],
  'Message to buy': ['ផ្ញើសារដើម្បីទិញ', 'Message to buy'],
  'Display language': ['ភាសាបង្ហាញ', 'Display language'],
  Khmer: ['ខ្មែរ', 'Khmer'],
  English: ['អង់គ្លេស', 'English'],
  'Language updated': ['បានប្ដូរភាសារួចរាល់', 'Language updated'],
  'Download TV App': ['ទាញយកកម្មវិធីទូរទស្សន៍', 'Download TV App'],
  'Enjoy now': ['ចាប់ផ្ដើមប្រើឥឡូវនេះ', 'Enjoy now'],
  Subtitles: ['ចំណងជើងរង', 'Subtitles'],
  On: ['បើក', 'On'],
  Off: ['បិទ', 'Off'],
  enabled: ['បានបើក', 'enabled'],
  disabled: ['បានបិទ', 'disabled'],
  'App appearance': ['រូបរាងកម្មវិធី', 'App appearance'],
  'VIP Membership': ['សមាជិក VIP', 'VIP Membership'],
  Close: ['បិទ', 'Close'],
  'Login to unlock more content': ['ចូលគណនីដើម្បីមើលមាតិកាបន្ថែម', 'Log in to unlock more content'],
  'Log in with password': ['ចូលគណនីដោយប្រើពាក្យសម្ងាត់', 'Log in with password'],
  'Log in with mobile number': ['ចូលគណនីដោយប្រើលេខទូរសព្ទ', 'Log in with mobile number'],
  'Phone number': ['លេខទូរសព្ទ', 'Phone number'],
  'Email or mobile number': ['អ៊ីមែល ឬលេខទូរសព្ទ', 'Email or mobile number'],
  Password: ['ពាក្យសម្ងាត់', 'Password'],
  'Enter password': ['បញ្ចូលពាក្យសម្ងាត់', 'Enter password'],
  'Hide password': ['លាក់ពាក្យសម្ងាត់', 'Hide password'],
  'Show password': ['បង្ហាញពាក្យសម្ងាត់', 'Show password'],
  'Recover password': ['ស្ដារពាក្យសម្ងាត់', 'Recover password'],
  'Signing in…': ['កំពុងចូលគណនី…', 'Signing in…'],
  Login: ['ចូលគណនី', 'Login'],
  'Login indicates you agree to the': ['ការចូលគណនីមានន័យថាអ្នកយល់ព្រមតាម', 'By logging in, you agree to the'],
  'Terms of Service': ['លក្ខខណ្ឌប្រើប្រាស់', 'Terms of Service'],
  and: ['និង', 'and'],
  'Privacy Policy': ['គោលការណ៍ឯកជនភាព', 'Privacy Policy'],
  Register: ['ចុះឈ្មោះ', 'Register'],
  'ទស្សនា': ['ទស្សនា', 'Watch'],
  'រឿង': ['រឿង', 'Stories'],
  'កម្មវិធីទស្សនារឿងកម្រិត 4K Ultra HD': ['កម្មវិធីទស្សនារឿងកម្រិត 4K Ultra HD', '4K Ultra HD Streaming App'],
  'ចូលទស្សនារឿង': ['ចូលទស្សនារឿង', 'Sign in to Huang+'],
  'ចូលគណនីតាមលេខទូរសព្ទ ឬ Google យ៉ាងងាយស្រួល': ['ចូលគណនីតាមលេខទូរសព្ទ ឬ Google យ៉ាងងាយស្រួល', 'Sign in easily with your phone number or Google.'],
  'លេខទូរសព្ទ (Phone)': ['លេខទូរសព្ទ', 'Phone number'],
  'លេខទូរសព្ទរបស់អ្នក': ['លេខទូរសព្ទរបស់អ្នក', 'Your phone number'],
  '12 345 678 ឬ 012345678': ['12 345 678 ឬ 012345678', '12 345 678 or 012345678'],
  'ពាក្យសម្ងាត់ (Password)': ['ពាក្យសម្ងាត់', 'Password'],
  'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក': ['បញ្ចូលពាក្យសម្ងាត់របស់អ្នក', 'Enter your password'],
  'ចូលគណនី (Login)': ['ចូលគណនី', 'Sign in'],
  'មិនទាន់មានគណនីមែនទេ?': ['មិនទាន់មានគណនីមែនទេ?', 'Don’t have an account yet?'],
  'បង្កើតគណនីថ្មី (ចុះឈ្មោះ)': ['បង្កើតគណនីថ្មី', 'Create an account'],
  'ចុចប៊ូតុងខាងក្រោមដើម្បីចូលប្រើប្រាស់ភ្លាមៗ៖': ['ចុចប៊ូតុងខាងក្រោមដើម្បីចូលប្រើប្រាស់ភ្លាមៗ៖', 'Use the button below to sign in instantly:'],
  'ត្រឡប់ទៅទំព័រដើម': ['ត្រឡប់ទៅទំព័រដើម', 'Back to home'],
  'សូមបញ្ចូលលេខទូរសព្ទ និងពាក្យសម្ងាត់របស់អ្នក': ['សូមបញ្ចូលលេខទូរសព្ទ និងពាក្យសម្ងាត់របស់អ្នក', 'Enter your phone number and password.'],
  'លេខទូរសព្ទ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវឡើយ': ['លេខទូរសព្ទ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវទេ', 'The phone number or password is incorrect.'],
  'សំណើស្នើសុំដោះសោរត្រូវបានផ្ញើទៅកាន់ Admin រួចរាល់ហើយ!': ['សំណើស្នើសុំដោះសោរត្រូវបានផ្ញើទៅ Admin រួចរាល់ហើយ!', 'Your account review request has been sent to the admin.'],
  'មានបញ្ហាក្នុងការផ្ញើសំណើ': ['មានបញ្ហាក្នុងការផ្ញើសំណើ', 'There was a problem sending your request.'],
  'មិនអាចភ្ជាប់ទៅកាន់ Server បានទេ': ['មិនអាចភ្ជាប់ទៅ Server បានទេ', 'Could not connect to the server.'],
  'គណនីរបស់អ្នកត្រូវបានផ្អាកដំណើរការ។ សូមដាក់ពាក្យស្នើសុំដោះសោរទៅកាន់ Admin៖': ['គណនីរបស់អ្នកត្រូវបានផ្អាក។ សូមផ្ញើសំណើពិនិត្យឡើងវិញទៅ Admin៖', 'Your account is suspended. Send an appeal to the admin:'],
  'ដាក់ពាក្យស្នើសុំដោះសោរ': ['ដាក់ពាក្យស្នើសុំដោះសោរ', 'Submit an appeal'],
  'ពាក្យស្នើសុំដោះសោរគណនី': ['ពាក្យស្នើសុំដោះសោរគណនី', 'Account appeal'],
  'បោះបង់': ['បោះបង់', 'Cancel'],
  'Admin នឹងពិនិត្យ និងដោះសោរជូនអ្នកក្នុងពេលឆាប់ៗ!': ['Admin នឹងពិនិត្យសំណើរបស់អ្នកក្នុងពេលឆាប់ៗនេះ។', 'The admin will review your request soon.'],
  'ឈ្មោះគណនី / Email របស់អ្នក៖': ['ឈ្មោះគណនី ឬអ៊ីមែលរបស់អ្នក៖', 'Your account name or email:'],
  'ឧ. your_email@gmail.com ឬ 012345678': ['ឧ. your_email@gmail.com ឬ 012345678', 'e.g. your_email@gmail.com or 012345678'],
  'មូលហេតុស្នើសុំដោះសោរ៖': ['មូលហេតុស្នើសុំដោះសោរ៖', 'Reason for your appeal:'],
  'ឧ. ខ្ញុំច្រឡំដៃចុច F12 / Shortcut សូម Admin ជួយដោះសោរគណនីខ្ញុំវិញផង...': ['ឧ. សូមជួយពិនិត្យមូលហេតុដែលគណនីខ្ញុំត្រូវបានផ្អាក...', 'e.g. Please review why my account was suspended…'],
  'ព័ត៌មានទំនាក់ទំនង (Telegram ឬលេខទូរស័ព្ទ) [បើមាន]៖': ['ព័ត៌មានទំនាក់ទំនង (Telegram ឬលេខទូរសព្ទ) [បើមាន]៖', 'Contact details (Telegram or phone number, optional):'],
  'ឧ. @my_telegram ឬ 012345678': ['ឧ. @my_telegram ឬ 012345678', 'e.g. @my_telegram or 012345678'],
  'កំពុងផ្ញើសំណើ...': ['កំពុងផ្ញើសំណើ...', 'Sending request…'],
  'ផ្ញើសំណើទៅកាន់ Admin': ['ផ្ញើសំណើទៅ Admin', 'Send request to admin'],
  'ចុះឈ្មោះ': ['ចុះឈ្មោះ', 'Register'],
  'សូមបញ្ចូលលេខទូរសព្ទរបស់អ្នក': ['សូមបញ្ចូលលេខទូរសព្ទរបស់អ្នក', 'Enter your phone number.'],
  'សូមបញ្ចូលពាក្យសម្ងាត់': ['សូមបញ្ចូលពាក្យសម្ងាត់', 'Enter your password.'],
  'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ': ['ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ', 'Password must be at least 6 characters.'],
  'ពាក្យសម្ងាត់ទាំង ២ មិនដូចគ្នាទេ': ['ពាក្យសម្ងាត់ទាំង ២ មិនដូចគ្នាទេ', 'The passwords do not match.'],
  'បរាជ័យក្នុងការចុះឈ្មោះគណនី': ['បរាជ័យក្នុងការចុះឈ្មោះគណនី', 'Could not create your account.'],
  'បង្កើតគណនីថ្មី (Register)': ['បង្កើតគណនីថ្មី', 'Create an account'],
  'ចុះឈ្មោះជាមួយលេខទូរសព្ទ និងពាក្យសម្ងាត់ងាយស្រួល': ['ចុះឈ្មោះជាមួយលេខទូរសព្ទ និងពាក្យសម្ងាត់', 'Create an account with your phone number and password.'],
  'ឈ្មោះគណនី (Username / ឈ្មោះហៅក្រៅ) [Optional]': ['ឈ្មោះគណនី (ស្រេចចិត្ត)', 'Username (optional)'],
  'ពាក្យសម្ងាត់ (យ៉ាងតិច ៦ តួ)': ['ពាក្យសម្ងាត់ (យ៉ាងតិច ៦ តួ)', 'Password (at least 6 characters)'],
  'កំណត់ពាក្យសម្ងាត់': ['កំណត់ពាក្យសម្ងាត់', 'Create a password'],
  'ផ្ទៀងផ្ទាត់ពាក្យសម្ងាត់ម្ដងទៀត': ['ផ្ទៀងផ្ទាត់ពាក្យសម្ងាត់ម្ដងទៀត', 'Confirm your password'],
  'បញ្ចូលពាក្យសម្ងាត់ដូចខាងលើ': ['បញ្ចូលពាក្យសម្ងាត់ដូចខាងលើ', 'Re-enter your password'],
  'បង្កើតគណនី (Sign Up)': ['បង្កើតគណនី', 'Create account'],
  'មានគណនីរួចហើយ?': ['មានគណនីរួចហើយ?', 'Already have an account?'],
  'ចូលគណនី (Sign In)': ['ចូលគណនី', 'Sign in'],
  'ចុចប៊ូតុងខាងក្រោមដើម្បីបង្កើតគណនីភ្លាមៗ៖': ['ចុចប៊ូតុងខាងក្រោមដើម្បីបង្កើតគណនីភ្លាមៗ៖', 'Use the button below to create your account:'],
  'Premium is active on your account. You can watch every available episode.': ['គណនីរបស់អ្នកមាន Premium សកម្ម។ អ្នកអាចមើលគ្រប់ភាគដែលមាន។', 'Premium is active on your account. You can watch every available episode.'],
  'Premium membership is arranged through Telegram. Message the admin to ask about access.': ['ការទិញ Premium ធ្វើតាម Telegram។ សូមផ្ញើសារទៅ Admin ដើម្បីសួរអំពីការបើកសិទ្ធិ។', 'Premium membership is arranged through Telegram. Message the admin to ask about access.'],
  'Message on Telegram': ['ផ្ញើសារតាម Telegram', 'Message on Telegram'],
  Back: ['ត្រឡប់ក្រោយ', 'Back'],
  'Account and Security': ['គណនី និងសុវត្ថិភាព', 'Account and Security'],
  'Personal Data': ['ព័ត៌មានផ្ទាល់ខ្លួន', 'Personal Data'],
  'Sign-in options': ['ជម្រើសចូលគណនី', 'Sign-in options'],
  'Playback & Download': ['ការចាក់វីដេអូ និងការទាញយក', 'Playback & Download'],
  'Autoplay next episode': ['ចាក់ភាគបន្ទាប់ដោយស្វ័យប្រវត្តិ', 'Autoplay next episode'],
  'Data saver': ['សន្សំទិន្នន័យអ៊ីនធឺណិត', 'Data saver'],
  'Reduce motion': ['កាត់បន្ថយចលនា', 'Reduce motion'],
  Privacy: ['ឯកជនភាព', 'Privacy'],
  'Hide promotions': ['លាក់ការផ្សព្វផ្សាយ', 'Hide promotions'],
  'Storage & App': ['ទំហំផ្ទុក និងកម្មវិធី', 'Storage & App'],
  'Clear cache': ['សម្អាតទិន្នន័យបណ្ដោះអាសន្ន', 'Clear cache'],
  'Reload app': ['ផ្ទុកកម្មវិធីឡើងវិញ', 'Reload app'],
  'Temporary app cache cleared. Your downloads and sign-in are unchanged.': ['បានសម្អាតទិន្នន័យបណ្ដោះអាសន្ន។ ការទាញយក និងការចូលគណនីរបស់អ្នកនៅដដែល។', 'Temporary app cache cleared. Your downloads and sign-in are unchanged.'],
  'Switch accounts': ['ប្ដូរគណនី', 'Switch accounts'],
  'Add account': ['បន្ថែមគណនី', 'Add Account'],
  'Log out': ['ចាកចេញ', 'Log out'],
  'Self-service': ['ជំនួយដោយខ្លួនឯង', 'Self-service'],
  'Manage VIP': ['គ្រប់គ្រង VIP', 'Manage VIP'],
  Payment: ['ការទូទាត់', 'Payment'],
  'Playback and account': ['ការចាក់វីដេអូ និងគណនី', 'Playback and account'],
  'Contact support on Telegram': ['ទាក់ទងផ្នែកជំនួយតាម Telegram', 'Contact support on Telegram'],
  'My downloads': ['ការទាញយករបស់ខ្ញុំ', 'My downloads'],
  'Profile saved': ['បានរក្សាទុកព័ត៌មានគណនីរួចរាល់', 'Profile saved'],
  'Could not save changes. Please try again.': ['មិនអាចរក្សាទុកការកែប្រែបានទេ។ សូមព្យាយាមម្ដងទៀត។', 'Could not save changes. Please try again.'],
  'Sign in to manage your profile.': ['សូមចូលគណនីដើម្បីគ្រប់គ្រងព័ត៌មានផ្ទាល់ខ្លួន។', 'Sign in to manage your profile.'],
  'Profile image': ['រូបភាពគណនី', 'Profile image'],
  Name: ['ឈ្មោះ', 'Name'],
  'Profile image URL': ['តំណរូបភាពគណនី', 'Profile image URL'],
  Email: ['អ៊ីមែល', 'Email'],
  'Saving…': ['កំពុងរក្សាទុក…', 'Saving…'],
  'Save changes': ['រក្សាទុកការកែប្រែ', 'Save changes'],
  'Account ID': ['លេខសម្គាល់គណនី', 'Account ID'],
  'How do I join VIP?': ['តើខ្ញុំចូលជាសមាជិក VIP ដោយរបៀបណា?', 'How do I join VIP?'],
  'Open VIP Membership, choose a plan, and follow the payment instructions shown for that plan. Your membership is activated after payment review.': ['បើកសមាជិកភាព VIP ជ្រើសរើសកញ្ចប់ ហើយអនុវត្តតាមការណែនាំទូទាត់។ សមាជិកភាពនឹងដំណើរការបន្ទាប់ពីពិនិត្យការទូទាត់។', 'Open VIP Membership, choose a plan, and follow the payment instructions shown for that plan. Your membership is activated after payment review.'],
  'What payment methods are supported?': ['តើអាចទូទាត់តាមវិធីណាខ្លះ?', 'What payment methods are supported?'],
  'Available methods are shown in the secure checkout for your region. If no method is available, contact support before sending payment.': ['វិធីទូទាត់ដែលអាចប្រើបាននឹងបង្ហាញនៅទំព័រទូទាត់។ បើមិនឃើញវិធីទូទាត់ សូមទាក់ទងផ្នែកជំនួយមុនផ្ញើប្រាក់។', 'Available methods are shown in the secure checkout for your region. If no method is available, contact support before sending payment.'],
  'What should I do if payment failed?': ['តើគួរធ្វើអ្វីបើការទូទាត់បរាជ័យ?', 'What should I do if payment failed?'],
  'Do not pay again immediately. Keep your receipt and contact support with your account name and transaction details.': ['កុំទូទាត់ម្ដងទៀតភ្លាមៗ។ រក្សាបង្កាន់ដៃ ហើយទាក់ទងផ្នែកជំនួយជាមួយឈ្មោះគណនី និងព័ត៌មានប្រតិបត្តិការ។', 'Do not pay again immediately. Keep your receipt and contact support with your account name and transaction details.'],
  'How do I cancel automatic renewal?': ['តើបោះបង់ការបន្តសមាជិកភាពដោយស្វ័យប្រវត្តិដូចម្ដេច?', 'How do I cancel automatic renewal?'],
  'Huang Anime plans are processed as manual payments. There is no automatic renewal unless the checkout explicitly says otherwise.': ['កញ្ចប់ Huang Anime ទូទាត់ដោយដៃ ហើយមិនបន្តដោយស្វ័យប្រវត្តិទេ លុះត្រាតែទំព័រទូទាត់បញ្ជាក់ផ្សេងពីនេះ។', 'Huang Anime plans are processed as manual payments. There is no automatic renewal unless the checkout explicitly says otherwise.'],
  'Where are my downloads?': ['តើវីដេអូដែលបានទាញយកនៅឯណា?', 'Where are my downloads?'],
  'Open Me → Downloads. Downloads are stored on this device and may not be available in a different browser or device.': ['បើក គណនី → ទាញយក។ ឯកសារទាញយករក្សាទុកលើឧបករណ៍នេះ ហើយប្រហែលមិនមាននៅលើកម្មវិធីរុករក ឬឧបករណ៍ផ្សេងទេ។', 'Open Me → Downloads. Downloads are stored on this device and may not be available in a different browser or device.'],
  'Friend Referral Rewards': ['រង្វាន់ណែនាំមិត្តភក្តិ', 'Friend Referral Rewards'],
  Standard: ['សមាជិកធម្មតា', 'Standard'],
  Active: ['សកម្ម', 'Active'],
  'No expiry date': ['គ្មានថ្ងៃផុតកំណត់', 'No expiry date'],
  'No active VIP plan': ['មិនមានកញ្ចប់ VIP សកម្មទេ', 'No active VIP plan'],
  Expired: ['ផុតកំណត់', 'Expired'],
  Expires: ['ផុតកំណត់', 'Expires'],
  'VIP benefits': ['អត្ថប្រយោជន៍ VIP', 'VIP benefits'],
  'Upgrade VIP': ['ដំឡើងទៅ VIP', 'Upgrade VIP'],
  'Free trial active for one series · expires': ['សាកល្បងឥតគិតថ្លៃសម្រាប់រឿង ១ · ផុតកំណត់', 'Free trial active for one series · expires'],
  'Account information': ['ព័ត៌មានគណនី', 'Account information'],
  'Telegram account': ['គណនី Telegram', 'Telegram account'],
  'Account and viewing settings': ['ការកំណត់គណនី និងការទស្សនា', 'Account and viewing settings'],
  'Default picture quality': ['កម្រិតរូបភាពលំនាំដើម', 'Default picture quality'],
  'VIP membership': ['សមាជិកភាព VIP', 'VIP membership'],
  'Lifetime membership': ['សមាជិកភាពពេញមួយជីវិត', 'Lifetime membership'],
  'Standard plan': ['កញ្ចប់ធម្មតា', 'Standard plan'],
  'UI and display settings': ['ការកំណត់រូបរាង និងការបង្ហាញ', 'UI and display settings'],
  'Eye comfort mode': ['របៀបស្រួលភ្នែក', 'Eye comfort mode'],
  'Clean UI Mode': ['របៀបសាមញ្ញ', 'Clean UI Mode'],
  Recommended: ['ណែនាំ', 'Recommended'],
  'Simplify animations and poster labels.': ['បិទចលនា 3D និងសម្រួលស្លាកលើ Poster ឲ្យមើលស្រួល', 'Reduce 3D animation and simplify poster labels.'],
  'Reduce motion and glow': ['កាត់បន្ថយចលនា និងពន្លឺ', 'Reduce motion and glow'],
  'Turn off neon pulses and intense movement.': ['បិទពន្លឺ Neon និងចលនាខ្លាំងៗ', 'Turn off neon pulses and intense movement.'],
  'Hide promotions and lucky wheel': ['លាក់ការផ្សាយ និងកង់សំណាង', 'Hide promotions and lucky wheel'],
  'Hide large promotions to focus on watching.': ['លាក់ផ្ទាំងផ្សាយធំៗ ដើម្បីផ្ដោតលើការទស្សនា', 'Hide large promotions to focus on watching.'],
  'Playback settings': ['ការកំណត់ការចាក់វីដេអូ', 'Playback settings'],
  'VIP prizes up to 3 months': ['ឈ្នះរង្វាន់ VIP រហូតដល់ ៣ ខែ', 'Win up to 3 months of VIP'],
  'VIP Lucky Wheel': ['កង់សំណាង VIP', 'VIP Lucky Wheel'],
  'Spin after buying VIP.': ['ទិញ VIP ម្ដង អាចចាប់រង្វាន់បានម្ដង', 'Buy VIP once and spin once.'],
  'Spin now': ['ចាប់រង្វាន់', 'Spin now'],
  'Official Telegram channel': ['ប៉ុស្តិ៍ Telegram ផ្លូវការ', 'Official Telegram channel'],
  'Join channel': ['ចូលរួម Channel', 'Join channel'],
  'Daily updates about new donghua and anime on Telegram.': ['ទទួលដំណឹងរឿងចិន និង Anime ថ្មីៗរាល់ថ្ងៃតាម Telegram', 'Get daily updates about new donghua and anime on Telegram.'],
  'Latest version': ['កំណែចុងក្រោយ', 'Latest version'],
  'Temporary data (Cache):': ['ទិន្នន័យផ្ទុកបណ្ដោះអាសន្ន (Cache):', 'Temporary data (Cache):'],
  'Clear Cache': ['សម្អាត Cache', 'Clear Cache'],
  'Cache cleared.': ['បានសម្អាត Cache រួចរាល់!', 'Cache cleared.'],
  'Support and security': ['ជំនួយ និងសុវត្ថិភាព', 'Support and security'],
  'Customer support': ['ផ្នែកបម្រើអតិថិជន និងជំនួយ', 'Customer support'],
  'Language: Khmer': ['ភាសា៖ ខ្មែរ', 'Language: Khmer'],
  'Language: English': ['ភាសា៖ អង់គ្លេស', 'Language: English'],
  'My library': ['បណ្ណាល័យរបស់ខ្ញុំ', 'My Library'],
  'Saved titles': ['បញ្ជីរក្សាទុក', 'Saved titles'],
  'Watch history': ['ប្រវត្តិទស្សនា', 'Watch history'],
  'No saved titles yet': ['មិនទាន់មានរឿងក្នុងបញ្ជីរក្សាទុកនៅឡើយទេ', 'No saved titles yet'],
  'Find a title and save it to watch later.': ['ស្វែងរករឿងដែលអ្នកចូលចិត្ត ហើយចុចប៊ូតុងរក្សាទុក ដើម្បីងាយស្រួលមើលពេលក្រោយ។', 'Find a title and save it to watch later.'],
  'Browse titles': ['រុករករឿង', 'Browse titles'],
  'No watch history yet': ['មិនទាន់មានប្រវត្តិទស្សនានៅឡើយទេ', 'No watch history yet'],
  'Watched episodes appear here.': ['ភាគរឿងដែលអ្នកបានមើលនឹងបង្ហាញនៅទីនេះដោយស្វ័យប្រវត្តិ។', 'Episodes you watch will appear here automatically.'],
  Episode: ['ភាគ', 'Episode'],
  'Delete watch history': ['លុបប្រវត្តិទស្សនាទាំងអស់', 'Delete watch history'],
  'Are you sure you want to clear all viewing history?': ['តើអ្នកពិតជាចង់លុបប្រវត្តិទស្សនាទាំងអស់ចេញពីគណនីមែនទេ?', 'Are you sure you want to clear all viewing history?'],
  'Delete all': ['លុបទាំងអស់', 'Delete all'],
  'Please sign in to view your history.': ['សូមចូលគណនីដើម្បីពិនិត្យប្រវត្តិទស្សនា។', 'Please sign in to view your history.'],
  'Sign in': ['ចូលគណនី', 'Sign in'],
  'Continue with Google': ['បន្តជាមួយ Google', 'Continue with Google'],
  'លេខទូរសព្ទ (Phone Number)': ['លេខទូរសព្ទ', 'Phone number'],
  '12 345 678 (Smart / Cellcard / Metfone)': ['12 345 678 (Smart / Cellcard / Metfone)', '12 345 678 (Smart / Cellcard / Metfone)'],
  'យើងនឹងផ្ញើលេខកូដសម្ងាត់ ៦ ខ្ទង់តាមសារ SMS ដើម្បីផ្ទៀងផ្ទាត់': ['យើងនឹងផ្ញើលេខកូដ ៦ ខ្ទង់តាម SMS ដើម្បីផ្ទៀងផ្ទាត់', 'We’ll send a 6-digit verification code by SMS.'],
  'ឈ្មោះគណនី (ស្រេចចិត្ត - Display Name)': ['ឈ្មោះគណនី (ស្រេចចិត្ត)', 'Display name (optional)'],
  'ឧទាហរណ៍៖ Dara_Nami': ['ឧទាហរណ៍៖ Dara_Nami', 'e.g. Dara_Nami'],
  'ផ្ញើលេខកូដ OTP តាម SMS': ['ផ្ញើលេខកូដ OTP តាម SMS', 'Send verification code by SMS'],
  'បញ្ចូលលេខកូដសម្ងាត់ OTP': ['បញ្ចូលលេខកូដ OTP', 'Enter verification code'],
  'បានផ្ញើទៅកាន់លេខ': ['បានផ្ញើទៅលេខ', 'Sent to'],
  'លេខកូដ OTP តេស្ត៖': ['លេខកូដ OTP តេស្ត៖', 'Test verification code:'],
  'បំពេញស្វ័យប្រវត្ត': ['បំពេញស្វ័យប្រវត្ត', 'Fill automatically'],
  'ប្តូរលេខទូរសព្ទ': ['ប្ដូរលេខទូរសព្ទ', 'Change phone number'],
  'ផ្ញើម្ដងទៀត': ['ផ្ញើម្ដងទៀត', 'Resend code'],
  'ផ្ញើម្ដងទៀតក្នុង': ['ផ្ញើម្ដងទៀតក្នុង', 'Resend in'],
  'ផ្ទៀងផ្ទាត់ & ចូលគណនី (Confirm OTP)': ['ផ្ទៀងផ្ទាត់ និងចូលគណនី', 'Verify and sign in'],
  'សូមបញ្ចូលលេខទូរសព្ទឱ្យបានត្រឹមត្រូវ (ឧទាហរណ៍៖ 012 345 678)': ['សូមបញ្ចូលលេខទូរសព្ទឱ្យបានត្រឹមត្រូវ (ឧទាហរណ៍៖ 012 345 678)', 'Enter a valid phone number (e.g. 012 345 678).'],
  'បរាជ័យក្នុងការផ្ញើសារ OTP សូមព្យាយាមម្ដងទៀត': ['បរាជ័យក្នុងការផ្ញើលេខកូដ។ សូមព្យាយាមម្ដងទៀត។', 'Could not send the verification code. Please try again.'],
  'សូមបញ្ចូលលេខកូដសម្ងាត់ OTP ឱ្យគ្រប់ ៦ ខ្ទង់': ['សូមបញ្ចូលលេខកូដ OTP ឲ្យគ្រប់ ៦ ខ្ទង់', 'Enter the full 6-digit verification code.'],
  'លេខកូដ OTP មិនត្រឹមត្រូវទេ សូមពិនិត្យម្ដងទៀត': ['លេខកូដ OTP មិនត្រឹមត្រូវទេ សូមពិនិត្យម្ដងទៀត', 'That verification code is incorrect. Please check it and try again.'],
  'កំពុងបើក Google Login...': ['កំពុងបើក Google Login...', 'Opening Google sign-in…'],
  'កំពុងផ្ទៀងផ្ទាត់ជាមួយ Server...': ['កំពុងផ្ទៀងផ្ទាត់ជាមួយ Server...', 'Verifying with the server…'],
  'កំពុងដំណើរការ...': ['កំពុងដំណើរការ...', 'Please wait…'],
  'episodes watched': ['ភាគបានទស្សនា', 'episodes watched'],
  'Start watching to track your episodes.': ['ចាប់ផ្ដើមទស្សនារឿង ដើម្បីតាមដានភាគរបស់អ្នក!', 'Start watching to track your episodes.'],
  'Watch now': ['ចាប់ផ្ដើមទស្សនា', 'Watch now'],
  'Watched': ['មើលបាន', 'Watched'],
  'Remove from history': ['ដកចេញពីប្រវត្តិទស្សនា', 'Remove from history'],
  'Saved': ['បានរក្សាទុក', 'Saved'],
  'Add to My List': ['បញ្ចូលក្នុងបញ្ជីរបស់ខ្ញុំ', 'Add to My List'],
  'Remove from My List': ['ដកចេញពីបញ្ជីរបស់ខ្ញុំ', 'Remove from My List'],
  'Play now': ['ចាក់ទស្សនា', 'Play now'],
  'Continue from where you left off': ['បន្តទស្សនាពីកន្លែងចាស់', 'Continue watching'],
  'Clear all history': ['លុបប្រវត្តិទាំងអស់', 'Clear all history'],
  'Remove item': ['លុបចេញ', 'Remove item'],
  Japanese: ['ជប៉ុន', 'Japanese'],
  Chinese: ['ចិន', 'Chinese'],
  'Completed through': ['ចប់ត្រឹម', 'Completed through'],
  'Offline mode': ['ទម្រង់គ្មានអ៊ីនធឺណិត', 'Offline mode'],
  'Downloaded episodes are available here offline.': ['អ្នកអាចទស្សនាភាគដែលបានទាញយកនៅទីនេះដោយមិនចាំបាច់ប្រើអ៊ីនធឺណិត។', 'Watch your downloaded episodes here without an internet connection.'],
  'Offline': ['ក្រៅបណ្ដាញ', 'Offline'],
  'Download library': ['បណ្ណាល័យទាញយកទុកមើល', 'Download library'],
  'Watch downloads any time, even without internet.': ['ទស្សនាភាគដែលបានទាញយកពេលណាក៏បាន ទោះគ្មានអ៊ីនធឺណិតក៏ដោយ។', 'Watch your downloads anytime, even without internet.'],
  Refresh: ['ធ្វើបច្ចុប្បន្នភាព', 'Refresh'],
  'Storage used': ['ទំហំផ្ទុកបានប្រើ', 'Storage used'],
  'Free space on device': ['ទំហំទំនេរនៅលើឧបករណ៍', 'Free space on device'],
  'Downloaded titles': ['ចំនួនរឿងដែលបានទាញយក', 'Downloaded titles'],
  'episodes saved': ['ភាគបានរក្សាទុក', 'episodes saved'],
  'Offline playback status': ['ស្ថានភាពមើលក្រៅបណ្ដាញ', 'Offline playback status'],
  Ready: ['រួចរាល់', 'Ready'],
  'Device storage': ['ទំហំផ្ទុកលើឧបករណ៍', 'Device storage'],
  'Play videos quickly and save mobile data.': ['ចាក់វីដេអូបានលឿន និងសន្សំទិន្នន័យអ៊ីនធឺណិត', 'Play videos quickly and save mobile data.'],
  'Downloading': ['កំពុងទាញយក', 'Downloading'],
  Cancel: ['បោះបង់', 'Cancel'],
  'No downloads yet': ['មិនទាន់មានវីដេអូទាញយកនៅឡើយទេ', 'No downloads yet'],
  'Download episodes from the watch page to watch them offline.': ['ចុចប៊ូតុងទាញយកនៅទំព័រមើលរឿង ដើម្បីរក្សាទុកភាគសម្រាប់មើលពេលគ្មានអ៊ីនធឺណិត។', 'Download episodes from the watch page to watch them offline.'],
  'Browse Donghua and Anime': ['រុករករឿងចិន និង Anime', 'Browse Donghua & Anime'],
  'Downloaded series': ['រឿងដែលបានទាញយករួច', 'Downloaded series'],
  'episodes stored': ['ភាគបានរក្សាទុក', 'episodes stored'],
  minutes: ['នាទី', 'min'],
  'Play offline': ['ចាក់ទស្សនាក្រៅបណ្ដាញ', 'Play offline'],
  'Delete from storage': ['លុបចេញពីឧបករណ៍', 'Delete from storage'],
  'Please sign in first': ['សូមចូលគណនីជាមុនសិន', 'Please sign in first'],
  'Sign in to watch in 4K.': ['ដើម្បីទស្សនាវីដេអូកម្រិត 4K UHD សូមចូលគណនីខាងក្រោម។', 'Sign in below to watch in 4K UHD.'],
  'Sign in with Google': ['ចូលគណនីជាមួយ Google', 'Sign in with Google'],
  'Special movie': ['ភាពយន្តពិសេស', 'Special movie'],
  'VIP members must also purchase this movie.': ['សមាជិក VIP ក៏ត្រូវទិញភាពយន្តនេះដែរ។', 'VIP members must also purchase this movie.'],
  'One-time purchase, watch forever.': ['បង់ប្រាក់តែម្តង អាចទស្សនារហូត។', 'One-time purchase. Watch forever.'],
  'Buy this movie on Telegram': ['ទិញភាពយន្តនេះតាម Telegram', 'Buy this movie on Telegram'],
  'VIP members only': ['សម្រាប់តែសមាជិក VIP ប៉ុណ្ណោះ', 'VIP members only'],
  'Free access expired.': ['ការចូលមើលឥតគិតថ្លៃបានផុតកំណត់ហើយ។ សូមទាក់ទង Admin ដើម្បីបើកសិទ្ធិ VIP។', 'Free access has expired. Contact the admin to enable VIP access.'],
  'This episode requires VIP.': ['ភាគនេះសម្រាប់តែសមាជិក VIP ប៉ុណ្ណោះ។ សូមដំឡើងគណនីដើម្បីទស្សនា។', 'This episode is for VIP members. Upgrade your account to watch.'],
  'Contact admin to upgrade VIP': ['ទាក់ទង Admin ដើម្បីដំឡើង VIP', 'Contact the admin to upgrade to VIP'],
  'VIP information': ['ព័ត៌មាន VIP', 'VIP information'],
  'Watch offline': ['ទស្សនាក្រៅបណ្ដាញ', 'Watch offline'],
  Downloaded: ['បានទាញយក', 'Downloaded'],
  Viewers: ['នាក់កំពុងមើល', 'viewers'],
  Previous: ['ភាគមុន', 'Previous'],
  Next: ['ភាគបន្ទាប់', 'Next'],
  'Special movie access': ['ភាពយន្តដុំពិសេស', 'Special movie access'],
  'All episodes': ['បញ្ជីភាគទាំងអស់', 'All episodes'],
  'Grid view': ['ទិដ្ឋភាពក្រឡា', 'Grid view'],
  'List view': ['ទិដ្ឋភាពបញ្ជី', 'List view'],
  'Search episode number...': ['ស្វែងរកលេខភាគ...', 'Search episode number...'],
  'No episodes found': ['រកមិនឃើញភាគដែលស្វែងរកឡើយ', 'No episodes found'],
  'Story details': ['ព័ត៌មានរឿង', 'Story details'],
  Notifications: ['សេចក្តីជូនដំណឹង', 'Notifications'],
  New: ['ថ្មី', 'new'],
  'New episodes and VIP updates': ['ដំណឹងភាគថ្មីៗ និងការជូនដំណឹង VIP', 'New episode releases and VIP updates'],
  'Mark all read': ['អានទាំងអស់', 'Mark all read'],
  'New episodes': ['ភាគថ្មី', 'New episodes'],
  'VIP & system': ['VIP និងប្រព័ន្ធ', 'VIP & system'],
  Unread: ['មិនទាន់អាន', 'Unread'],
  Following: ['កំពុងតាមដាន', 'Following'],
  'No notifications yet': ['មិនមានការជូនដំណឹងនៅឡើយទេ', 'No notifications yet'],
  'Updates will appear here.': ['ពេលមានភាគថ្មី ឬដំណឹងពិសេស វានឹងបង្ហាញនៅទីនេះ', 'New episodes and updates will appear here.'],
  Settings: ['ការកំណត់', 'Settings'],
  Search: ['ស្វែងរក', 'Search'],
  'Search results': ['លទ្ធផលស្វែងរក', 'Search results'],
  'Continue watching': ['បន្តទស្សនា', 'Continue watching'],
  'Recently watched': ['បានទស្សនាថ្មីៗ', 'Recently watched'],
  'No results found': ['រកមិនឃើញលទ្ធផលទេ', 'No results found'],
  'Loading...': ['កំពុងផ្ទុក...', 'Loading...'],
  'Help and Feedback': ['ជំនួយ និងមតិយោបល់', 'Help and Feedback'],
  'Genre': ['ប្រភេទ', 'Genre'],
  'Year': ['ឆ្នាំ', 'Year'],
  'Region': ['តំបន់', 'Region'],
  'All genres': ['គ្រប់ប្រភេទ', 'All genres'],
  'All years': ['គ្រប់ឆ្នាំ', 'All years'],
  'All regions': ['គ្រប់តំបន់', 'All regions'],
  'All': ['ទាំងអស់', 'All'],
  'Free': ['ឥតគិតថ្លៃ', 'Free'],
  'Sort:': ['តម្រៀប៖', 'Sort:'],
  'Latest': ['ថ្មីៗចុងក្រោយ', 'Latest'],
  Popular: ['ពេញនិយមបំផុត', 'Popular'],
  'Top rated': ['ពិន្ទុខ្ពស់', 'Top rated'],
  'No titles found': ['រកមិនឃើញរឿងឡើយ', 'No titles found'],
  'Try changing the category or filters.': ['សូមសាកល្បងជ្រើសរើសប្រភេទរឿង ឬលក្ខខណ្ឌផ្សេងទៀត', 'Try changing the category or filters.'],
  'Total titles': ['រឿងសរុប', 'Total titles'],
  'Category:': ['ប្រភេទ៖', 'Category:'],
  'Access:': ['សិទ្ធិមើល៖', 'Access:'],
  'Free Zone': ['តំបន់ទស្សនាឥតគិតថ្លៃ', 'Free Zone'],
  'All titles': ['រុករកបញ្ជីរឿងទាំងអស់', 'Browse all titles'],
  '🇨🇳 Donghua 3D': ['🇨🇳 រឿងចិន 3D', '🇨🇳 Donghua 3D'],
  '🇯🇵 Japanese anime': ['🇯🇵 រឿងគំនូរជីវចលជប៉ុន', '🇯🇵 Japanese anime'],
  '🎭 Drama': ['🎭 រឿងភាគ', '🎭 Drama'],
  '🎬 Movies': ['🎬 ភាពយន្ត', '🎬 Movies'],
  '🍿 Movies': ['🍿 ភាពយន្តដុំ', '🍿 Movies'],
  'All audio': ['សំឡេងទាំងអស់', 'All audio'],
  'Khmer dubbed': ['និយាយខ្មែរ', 'Khmer dubbed'],
  'Khmer subtitles': ['អក្សររត់ខ្មែរ', 'Khmer subtitles'],
  'Donghua 3D': ['រឿងចិន 3D', 'Donghua 3D'],
  'Japanese Anime': ['អានីមេជប៉ុន', 'Japanese anime'],
  'Movies (Movie)': ['ភាពយន្ត', 'Movies'],
  'Khmer dub': ['និយាយខ្មែរ (សំឡេង)', 'Khmer dub'],
  'Ongoing (status)': ['កំពុងចាក់ផ្សាយ', 'Ongoing'],
  'Completed (status)': ['ចប់ហើយ', 'Completed'],
  'Ongoing': ['កំពុងចាក់ផ្សាយ', 'Ongoing'],
  'Completed': ['ចប់ហើយ', 'Completed'],
  'Search title and advanced filters': ['ស្វែងរកចំណងជើងរឿង និងតម្រងកម្រិតខ្ពស់', 'Search titles and advanced filters'],
  Filters: ['តម្រងស្វែងរក', 'Filters'],
  'Enter a title to search...': ['វាយបញ្ចូលឈ្មោះរឿងដែលអ្នកចង់ស្វែងរក...', 'Enter a title to search...'],
  'Quick suggestions': ['លទ្ធផលណែនាំរហ័ស', 'Quick suggestions'],
  'Tap a title to watch': ['ចុចលើរឿងដើម្បីទស្សនា', 'Tap a title to watch'],
  'Filter options': ['កំណត់លក្ខខណ្ឌតម្រង', 'Filter options'],
  Reset: ['កំណត់ឡើងវិញ', 'Reset'],
  Type: ['ប្រភេទសាច់រឿង', 'Type'],
  Language: ['ភាសា និងសំឡេង', 'Language and audio'],
  Status: ['ស្ថានភាពផ្សាយ', 'Status'],
  'Sort by': ['តម្រៀបតាម', 'Sort by'],
  'Latest first': ['ចុងក្រោយបង្អស់', 'Latest first'],
  'Most viewed': ['មើលច្រើនជាងគេ', 'Most viewed'],
  'Highest rated': ['ពិន្ទុខ្ពស់ជាងគេ', 'Highest rated'],
  'Title A to Z': ['តាមតួអក្សរ A ដល់ Z', 'Title A to Z'],
  'Popular searches': ['ពាក្យពេញនិយមស្វែងរក', 'Popular searches'],
  'No matching results': ['រកមិនឃើញលទ្ធផលទេ', 'No matching results'],
  'Try another title or clear the search filters.': ['សាកល្បងវាយឈ្មោះរឿងផ្សេង ឬលុបតម្រងស្វែងរក។', 'Try another title or clear the search filters.'],
  'Clear all filters': ['លុបលក្ខខណ្ឌតម្រងទាំងអស់', 'Clear all filters'],
  'Results found': ['រកឃើញចំនួន', 'Results found'],
  titles: ['រឿង', 'titles'],
  'Using filters': ['កំពុងប្រើតម្រង', 'Using filters'],
  'Find a story you like': ['ស្វែងរករឿងដែលអ្នកចូលចិត្ត', 'Find a story you like'],
  'Search and watch popular titles in 4K.': ['ស្វែងរក និងទស្សនារឿងពេញនិយមកម្រិត 4K', 'Search and watch popular titles in 4K.'],
  'Title search and advanced filters': ['ស្វែងរកចំណងជើងរឿង និងតម្រងកម្រិតខ្ពស់', 'Title search and advanced filters'],
  'Search 4K anime and drama.': ['ស្វែងរករឿងចិន អានីមេជប៉ុន និងភាពយន្តកម្រិត 4K', 'Search anime, donghua, and movies in 4K.'],
  'Search anime, donghua, and movies in 4K.': ['ស្វែងរករឿងចិន អានីមេជប៉ុន និងភាពយន្តកម្រិត 4K', 'Search anime, donghua, and movies in 4K.'],
  'Search anime, donghua, or English title...': ['វាយបញ្ចូលឈ្មោះរឿងចិន 3D រឿងជប៉ុន ឬចំណងជើងជាភាសាខ្មែរ...', 'Search anime, donghua, or English title...'],
  'Search title': ['ស្វែងរក', 'Search'],
  'Clear search': ['លុបពាក្យស្វែងរក', 'Clear search'],
  'Quick suggestions count': ['លទ្ធផលណែនាំរហ័ស', 'Quick suggestions'],
  'Tap a title to watch.': ['ចុចលើរឿងដើម្បីទស្សនា', 'Tap a title to watch'],
  'Khmer subtitles (sub)': ['អក្សររត់ខ្មែរ', 'Khmer subtitles'],
  'All content': ['ទាំងអស់', 'All'],
  'All statuses': ['ទាំងអស់', 'All'],
  'Search popular titles': ['ពាក្យពេញនិយមស្វែងរក', 'Popular searches'],
  'No results for this search': ['រកមិនឃើញលទ្ធផលទេ', 'No results found'],
  'Try another title or reset filters.': ['សូមសាកល្បងវាយបញ្ចូលឈ្មោះរឿងផ្សេងទៀត ឬកំណត់តម្រងឡើងវិញ។', 'Try another title or reset filters.'],
  'Showing results': ['រកឃើញចំនួន', 'Showing results'],
  'Filter active': ['កំពុងប្រើតម្រង', 'Filters active'],
  'Search for something to watch': ['ស្វែងរករឿងដែលអ្នកចូលចិត្ត', 'Find a story you like'],
};

export function translate(text: string, language: AppLanguage): string {
  const value = translations[text];
  return value ? value[language === 'km' ? 0 : 1] : text;
}

interface LanguageState {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
}

function readLanguage(): AppLanguage {
  try {
    return localStorage.getItem('huang_app_language') === 'en' ? 'en' : 'km';
  } catch {
    return 'km';
  }
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: readLanguage(),
  setLanguage: (language) => {
    try { localStorage.setItem('huang_app_language', language); } catch { /* keep the in-memory preference */ }
    if (typeof document !== 'undefined') document.documentElement.lang = language;
    set({ language });
  },
}));
